android_homepage:
    path:     /index
    defaults: { _controller:AndroidBundle:Android:index }
    
android_homepage:
    path:     /
    defaults: { _controller:AndroidBundle:Android:index }


test:
    path:   /test
    defaults: {_controller:AndroidBundle:Android:test}

connexion:
    path:   /connexion/{login}/{password}
    defaults: {_controller:AndroidBundle:Android:connexion}
    
    
recupListeRapport:
    path:    /recupListeRapport/{idVisiteur}
    defaults: {_controller:AndroidBundle:Android:recupListeRapport}
    
ajouterRapport:
    path:    /ajouterRapport
    defaults: {_controller:AndroidBundle:Android:ajouterRapport}
    
recupListeRapportParDate:
    path:   /getLesRapportsParDate/{mois}/{annee}
    defaults: {_controller:AndroidBundle:Android:getLesRapportsParDate}